import { domEl } from '../../scripts/dom-helpers.js';
import { getMonthNumber, getNumberByPosition } from '../../scripts/utils.js';

/**
* Add creates and adds scope to the table headers
* @param {HTMLElement} row - The row that will contain the header (tr)
* @param {HTMLElement} cell - The cell that is the header (td --> gets transformed to th)
* @param {string} scope - The scope that the table cell should have once it is a th
*/
function createTableHeaders( row, cell, scope ) {
	const th = domEl( 'th', { 'scope': scope }, cell.innerText );

	if ( scope === 'row' ) {
		const sortValue = cell.dataset.sortValue;
		if( sortValue ) th.setAttribute( 'data-sort-value', sortValue );
		row.prepend( th );
	} else {
		row.append( th );
	}

	cell.remove();
}

/**
* Check the table type to see if its scrollable or not 
* @param {HTMLElement} block - The table generated by EDS
*/
function checkType( block ) {
	const c = block.classList;
	let type;
	
	if ( c.contains( 'col-header' ) ) {
		type = 'col-header';
	} else if ( c.contains( 'scrollable' ) ){
		type = 'scrollable';
	} else {
		type = 'default';
	}
	
	return type;
}

/**
 * Filtering by the header
 */

function createSort( block ) {
	const thead = block.querySelector( 'thead' );
	const ths = thead.querySelectorAll( 'th' );
	const tbody = block.querySelector( 'tbody' );

	const getRows = () => Array.from( tbody.querySelectorAll( 'tr' ) );

	// Build sortable header 
	ths.forEach( th =>{
		th.setAttribute( 'data-sortable', '' );
		th.setAttribute( 'role', 'columnheader' );
		th.setAttribute( 'aria-label', `${th.textContent.trim()}, sortable column, currently unsorted.` );

		const button = domEl( 'button', { 
			class: 'table__header__button',
			title: `Click to sort by ${th.textContent.trim()} in ascending order.`,
		} );
		th.append( button );
	} );

	// Precompute sort value
	function setSortValue( td ) {
		const text = td.textContent.trim();
		if( /^(-|)\d+(\.\d+)?%$/.test( text ) ) {
			td.setAttribute( 'data-sort-value', Number( text.replace( '%', '' ) ) /100 );
		}
		else if( /^(-|)\d+(\.|,|)(\d+)?$/.test( text ) ){
			td.setAttribute( 'data-sort-value', Number( text.replace( ',', '' ) ) );
		}
		else if( getNumberByPosition( text ) ){
			td.setAttribute( 'data-sort-value', getNumberByPosition( text ) );
		}
		else if( new Date( text ) != 'Invalid Date' ){
			td.setAttribute( 'data-sort-value', new Date( text ).getTime() );
		}
		else if( getMonthNumber( text ) ){
			td.setAttribute( 'data-sort-value', getMonthNumber( text ) );
		}
		else{
			td.setAttribute( 'data-sort-value', text );
		}
	}

	block.querySelectorAll( 'tbody td, tbody th' ).forEach( setSortValue );

	let activeColIndex = null;

	function compareValues( aVal, bVal, direction ){
		const aNum = Number( aVal );
		const bNum = Number( bVal );
		const bothNumeric = !Number.isNaN( aNum ) && !Number.isNaN( bNum );

		if ( bothNumeric ) {
			return direction === 'asc' ? aNum - bNum : bNum - aNum;
		}

		const aStr = String( aVal );
		const bStr = String( bVal );
		return direction === 'asc' ? aStr.localeCompare( bStr ): bStr.localeCompare( aStr ); 
	}

	function setActiveColumn( colIndex, rows ){		
		if ( activeColIndex !== null ) {
			for ( const row of rows ) {
				row.children[activeColIndex]?.removeAttribute( 'data-sort-active' );
			}
		}
		for ( const row of rows ) {
			row.children[colIndex]?.setAttribute( 'data-sort-active', 'true' );
		}
		activeColIndex = colIndex;
	}

	function toggleAriaSort( parentTh ) {
		let ascending = true;
		ths.forEach( ( th ) => {
			if ( th !== parentTh ) {
				th.removeAttribute( 'aria-sort' );
				return;
			}
			let cur = th.getAttribute( 'aria-sort' );
			if( cur === null ) cur = 'descending';
			const next = cur === 'ascending' ? 'descending' : 'ascending';
			th.querySelector( 'button' ).title = `Click to sort by ${th.textContent.trim()} in ${cur} order.`;
			th.ariaLabel = `${th.textContent.trim()}, sortable column, currently sorted ${next}.`;
			th.setAttribute( 'aria-sort', next );
			ascending = next === 'ascending';
		} );

		return ascending;
	}

	function handleSort( e ) {
		const parentTh = e.currentTarget.closest( 'th' );
		if ( !parentTh ) return;

		const colIndex = parentTh.cellIndex;
		const rows = getRows();
		const ascending = toggleAriaSort( parentTh );
		setActiveColumn( colIndex, rows ) ;
		
		rows.forEach( row =>{
			row.children[parent.colIndex]?.setAttribute( 'data-sort-active', 'true' );
		} );

		const sortable = rows.map( ( row ) => ( {
			row,
			value: row.children[colIndex]?.getAttribute( 'data-sort-value' ) ?? '',
		} ) );

		const dir = ascending ? 'asc' : 'desc';
		sortable.sort( ( a, b ) => compareValues( a.value, b.value, dir ) );

		const frag = document.createDocumentFragment();
		for ( const item of sortable ) frag.append( item.row );
		tbody.append( frag ); 
	}

	thead.querySelectorAll( 'button.table__header__button' )
		.forEach( ( btn ) => btn.addEventListener( 'click', handleSort ) );

}

/**
* Generates the table
* @param {HTMLElement} block - The table generated by EDS
*/
export default function decorate( block ) {
	const type = checkType( block );
	const table = block.querySelector( 'table' );
	const p = block.querySelector( 'p' );
	const caption = domEl( 'caption', {}, p );
	const tbody = table.querySelector( 'tbody' );
	const rows = tbody.querySelectorAll( 'tr' );
	let thead = null;
	let container = null;
	let newRows;
	
	table.classList.add( 'usa-table' );

	// create the header 
	thead = domEl( 'thead', {}, rows[0] );
	rows[0].querySelectorAll( 'td' ).forEach( ( cell ) => {
		createTableHeaders( rows[0], cell, 'col' );
	} );

	table.prepend( thead );
	if ( p ) {
		table.append( caption );
	}
	// grab the new Rows in the body after we generate the thead 
	newRows = tbody.querySelectorAll( 'tr' ); 

	if( block.classList.contains( 'sortable' ) ) createSort( block );
	
	// handle scrollable table 
	if ( type === 'scrollable' || type === 'col-header' ) {
		container = domEl( 'div', {class: 'usa-table-container--scrollable' }, table );
		if ( type === 'col-header' ) {
			newRows.forEach( ( row ) => {
				createTableHeaders( row, row.querySelector( 'td' ), 'row' );
			} );
		}
	} else { // handle stacked table 
		table.classList.add( 'usa-table--stacked' );
		const newHeaderRow = table.querySelectorAll( 'thead th' );
		newRows.forEach( ( row ) => {
			const tds = [...row.querySelectorAll( 'td' ) ]; // Get all td elements in this row
			[...newHeaderRow].map( ( th, index ) => {
				const dataLabel = th.textContent.trim();
				tds[index].dataset.label = dataLabel;
			} );
		} );
	}


	
	block.textContent = '';
	if ( container ) {
		block.append( container );
	} else {
		block.append( table );
	}
}